train:
  data_type: train
  data_folder_path: /g/data/wa66/Xiangyu/Data/DAIC-WOZ/Data
  label_csv_path: /g/data/wa66/Xiangyu/Data/DAIC-WOZ/Label/train_split_Depression_AVEC2017.csv
  output_path: /home/561/xz4320/Auto-Landmark/egs/DAIC/data/train
  dataset_name: 'DAIC'

dev:
  data_type: dev
  data_folder_path: /g/data/wa66/Xiangyu/Data/DAIC-WOZ/Data
  label_csv_path: /g/data/wa66/Xiangyu/Data/DAIC-WOZ/Label/dev_split_Depression_AVEC2017.csv
  output_path: /home/561/xz4320/Auto-Landmark/egs/DAIC/data/dev
  dataset_name: 'DAIC'